#!/usr/bin/env python3
"""Generates docs/API.md from the route decorators, so the documentation cannot drift from the code."""
import ast
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1] / "apps" / "api" / "app"
rows = []
for path in sorted(list((ROOT / "api").glob("*.py")) + [ROOT / "main.py"]):
    tree = ast.parse(path.read_text())
    prefix = ""
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Call) and getattr(node.value.func, "id", "") == "APIRouter":
            for kw in node.value.keywords:
                if kw.arg == "prefix":
                    prefix = kw.value.value
    for fn in [n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]:
        for dec in fn.decorator_list:
            if isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute) and dec.func.attr in ("get", "post", "patch", "delete", "put") and dec.args:
                src = ast.get_source_segment(path.read_text(), fn) or ""
                auth = "public" if "current_user" not in src and "membership" not in src and "load(" not in src else (
                    "owner/admin" if "ADMIN" in src else "owner/admin/researcher" if "WRITE" in src else "any member")
                doc = (ast.get_docstring(fn) or "").split("\n")[0]
                rows.append((prefix + dec.args[0].value, dec.func.attr.upper(), auth, fn.name, doc))
rows.sort(key=lambda r: (r[0], r[1]))
out = ["# API reference", "", "_Generated by `scripts/gen_api_doc.py` from the route decorators (auth column is derived from the handler source)._", "",
       "Authentication: httpOnly session cookie (browser; unsafe methods also need `X-CSRF-Token`) or `Authorization: Bearer` (API clients; sign up/in with `issue_token: true`).",
       "Errors: 401 unauthenticated, 403 role not allowed / CSRF failure, 404 resource missing **or not visible to you** (no existence leaks), 409 state conflict, 422 validation, 429 rate limited, 503 queue/db unavailable.", "",
       "| Method | Path | Access | Handler | Notes |", "|---|---|---|---|---|"]
out += [f"| {m} | `{p}` | {a} | `{n}` | {d} |" for p, m, a, n, d in rows]
out += ["", f"{len(rows)} endpoints.", ""]
(pathlib.Path(__file__).resolve().parents[1] / "docs" / "API.md").write_text("\n".join(out))
print(f"wrote docs/API.md ({len(rows)} endpoints)")
